name: Update Bankier RSS

on:
  schedule:
    - cron: '0 * * * *' # Co godzinę
  workflow_dispatch: # Możliwość ręcznego odpalenia

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: ambassadors/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedgen pytz

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "RSS-Bot"
          git config --global user.email "bot@github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || exit 0
          git push
